/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, a} from '@react-spring/three'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('3d/box.glb') // file path

  const playAudio = (isOpen) => {
    let audio
    isOpen ? audio = new Audio("/audio/close.mp3")
           : audio = new Audio("/audio/open.mp3")
    audio.volume = 0.1;
    audio.play()
  }

  const handleOpen = () => {
    props.setOpen(!props.open)
    playAudio(props.open)
  }

  const openChestAnimaiton = useSpring({
    rotation: props.open ? [0, 0, 0] : [1.61, 0, 0],
    position: props.open ? [0, -1.5, 0] : [0, 0, 0],
  })

  return (
    <group onClick={handleOpen} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[4.08, 5.9, -1.01]} rotation={[1.89, 0.88, -2.05]} />
        <group name="Camera" position={[7.36, 4.96, 6.93]} rotation={[1.24, 0.33, -0.76]} />
        <a.group rotation={openChestAnimaiton.position} name="Armature" position={[0, -0.99, 0]}> {/*spins chest*/}
          <primitive object={nodes.Bone} />
          {/* Top part of the chest */}
          <a.primitive rotation={openChestAnimaiton.rotation} object={nodes.Bone001} /> {/*opens chest*/}
          <skinnedMesh
            castShadow
            receiveShadow
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.Material}
            skeleton={nodes.Cube.skeleton}
          />
        </a.group>
      </group>
    </group>
  )
}

useGLTF.preload('/box.glb')
