/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Car({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('3d/car.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.08, 0.57, -0.31]} scale={[2.28, -0.33, 1]}>
        <mesh castShadow geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.ОКНО} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube_5.geometry} material={materials['Material.009']} />
      </group>
      <group position={[-1.28, 0.23, -1.24]} rotation={[Math.PI / 2, 0, 0]} scale={[0.16, 0.07, 0.16]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.ДИСК} />
      </group>
      <group position={[1.5, 0.23, 0.68]} rotation={[Math.PI / 2, 0, 0]} scale={[0.16, 0.07, 0.16]}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-1.28, 0.23, 0.63]} rotation={[Math.PI / 2, 0, 0]} scale={[0.16, 0.07, 0.16]}>
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Material.006']} />
      </group>
      <group position={[1.51, 0.25, -1.24]} rotation={[Math.PI / 2, 0, 0]} scale={[0.16, 0.07, 0.16]}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['ДИСК.001']} />
      </group>

    </group>
  )
}

useGLTF.preload('/car.glb')
